export function getHomePageStyles(isDarkTheme) {
  return {
      page: {
        minHeight: '100vh',
        background: '#f8fafc',
      },
      hero: {
        backgroundColor: '#0a1715',
        padding: '66px 24px 42px',
        position: 'relative',
        overflow: 'hidden',
        boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.08)',
      },
      heroGlow: {
        position: 'absolute',
        width: '600px',
        height: '600px',
        right: '-200px',
        top: '-260px',
        borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(212, 170, 94, 0.28), rgba(17, 49, 44, 0.08) 60%, transparent 72%)',
        filter: 'blur(2px)',
      },
      heroContent: {
        maxWidth: '1240px',
        margin: '0 auto',
        position: 'relative',
        zIndex: 1,
        display: 'grid',
        gridTemplateColumns: '1.2fr 0.8fr',
        gap: '22px',
        alignItems: 'center',
      },
      heroCopy: {
        maxWidth: '680px',
      },
      heroShell: {
        display: 'flex',
        justifyContent: 'flex-end',
        pointerEvents: 'none',
      },
      heroGlassCard: {
        width: '100%',
        maxWidth: '380px',
        borderRadius: '28px',
        padding: '18px',
        background: isDarkTheme ? 'linear-gradient(135deg, rgba(12,22,18,0.82), rgba(11,37,29,0.78))' : 'linear-gradient(135deg, rgba(255,255,255,0.20), rgba(255,255,255,0.08))',
        border: isDarkTheme ? '1px solid rgba(123,225,173,0.22)' : '1px solid rgba(255,255,255,0.20)',
        backdropFilter: 'blur(18px)',
        WebkitBackdropFilter: 'blur(18px)',
        boxShadow: '0 30px 64px rgba(7, 25, 23, 0.36), inset 0 1px 0 rgba(255,255,255,0.18)',
        color: '#fff',
      },
      heroGlassHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        marginBottom: '18px',
      },
      heroGlyph: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '30px',
        height: '30px',
        borderRadius: '10px',
        background: 'linear-gradient(135deg, rgba(212,170,94,0.35), rgba(255,255,255,0.14))',
        border: '1px solid rgba(255,255,255,0.18)',
        color: '#f9eec5',
        fontWeight: 800,
      },
      heroGlassTitle: {
        fontSize: '12px',
        textTransform: 'uppercase',
        letterSpacing: '1.1px',
        color: '#f5e3a8',
      },
      heroGlassGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
        gap: '12px',
      },
      heroGlassMetric: {
        padding: '12px 14px',
        borderRadius: '14px',
        background: 'rgba(255,255,255,0.08)',
        border: '1px solid rgba(255,255,255,0.12)',
      },
      heroMetricLabel: {
        display: 'block',
        fontSize: '9px',
        fontWeight: 700,
        letterSpacing: '0.9px',
        textTransform: 'uppercase',
        color: 'rgba(255,255,255,0.66)',
        marginBottom: '6px',
      },
      heroMetricValue: {
        fontSize: '16px',
        fontWeight: 800,
        color: '#ffffff',
        letterSpacing: '-0.03em',
      },
      eyebrow: {
        display: 'inline-flex',
        padding: '7px 13px',
        borderRadius: '999px',
        background: 'linear-gradient(135deg, rgba(255,255,255,0.18), rgba(194,220,200,0.12))',
        border: '1px solid rgba(212, 230, 219, 0.22)',
        color: '#fcedbf',
        fontSize: '12px',
        fontWeight: '700',
        letterSpacing: '0.2px',
        marginBottom: '15px',
        boxShadow: '0 10px 22px rgba(11, 58, 42, 0.12)',
      },
      title: {
        fontSize: 'clamp(40px, 5vw, 62px)',
        fontWeight: '800',
        color: '#fff',
        lineHeight: '1.08',
        marginBottom: '15px',
        letterSpacing: '-0.055em',
      },
      titleAccent: {
        color: '#f4d57f',
        display: 'inline-block',
        textShadow: '0 12px 28px rgba(244, 213, 127, 0.20)',
      },
      subtitle: {
        fontSize: '16px',
        color: 'rgba(255,255,255,0.84)',
        marginBottom: '22px',
        lineHeight: '1.65',
        maxWidth: '520px',
      },
      heroActions: {
        display: 'flex',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '16px',
        marginBottom: '0',
      },
      exploreBtn: {
        border: isDarkTheme ? '1px solid rgba(255,255,255,0.16)' : '1px solid rgba(255,255,255,0.22)',
        borderRadius: '13px',
        padding: '14px 20px',
        background: 'linear-gradient(135deg, #d8b977 0%, #bd8a4c 100%)',
        color: '#1d261d',
        fontSize: '13px',
        fontWeight: '800',
        cursor: 'pointer',
        boxShadow: '0 12px 26px rgba(164, 112, 43, 0.28)',
      },
      deliveryNote: {
        color: isDarkTheme ? 'rgba(255,255,255,0.82)' : 'rgba(255,255,255,0.78)',
        fontSize: '12px',
        fontWeight: '600',
      },
      heroStats: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '12px 22px',
        color: 'rgba(255,255,255,0.7)',
        fontSize: '11px',
      },
      heroStat: {
        color: '#fff',
      },
      heroTools: {
        maxWidth: '1240px',
        margin: '34px auto 0',
        position: 'relative',
        zIndex: 1,
      },
      featureSection: {
        maxWidth: '1280px',
        margin: '-18px auto 0',
        padding: '0 24px',
        position: 'relative',
        zIndex: 2,
      },
      featureGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '18px',
      },
      featureCard: {
        background: isDarkTheme ? 'linear-gradient(180deg, rgba(15,24,20,0.96), rgba(17,31,26,0.96))' : 'linear-gradient(180deg, rgba(255,255,255,0.98), rgba(240,252,245,0.96))',
        border: isDarkTheme ? '1px solid rgba(125,173,156,0.18)' : '1px solid rgba(20,100,70,0.12)',
        borderRadius: '20px',
        padding: '18px 18px',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '12px',
        boxShadow: isDarkTheme ? '0 18px 30px rgba(0, 0, 0, 0.18)' : '0 18px 30px rgba(11, 58, 42, 0.075)',
        backdropFilter: 'blur(10px)',
      },
      featureIcon: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '42px',
        height: '42px',
        background: 'linear-gradient(135deg, #edfdf4, #daf7e7)',
        borderRadius: '12px',
        fontSize: '20px',
        flexShrink: 0,
        boxShadow: 'inset 0 0 0 1px rgba(26,127,93,0.08)',
      },
      featureTitle: {
        margin: '0 0 4px',
        fontSize: '15px',
        fontWeight: '800',
        color: isDarkTheme ? '#edf9f1' : '#0d2a22',
      },
      featureText: {
        margin: 0,
        fontSize: '12px',
        lineHeight: 1.55,
        color: isDarkTheme ? '#b2c5ba' : '#5e6e66',
      },
      marketToggle: {
        display: 'flex',
        gap: '12px',
        justifyContent: 'flex-start',
        marginBottom: '14px',
        flexWrap: 'wrap',
      },
      marketBtn: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '10px',
        padding: '12px 26px',
        borderRadius: '40px',
        fontSize: '14px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        border: 'none',
        minWidth: '220px',
        lineHeight: 1.2,
      },
      marketBtnActive: {
        background: '#2c4842',
        color: '#ffffff',
        boxShadow: '0 8px 18px rgba(15, 31, 27, 0.18)',
        border: '1px solid rgba(255,255,255,0.18)',
        fontWeight: 800,
      },
      marketBtnInactive: {
        background: isDarkTheme ? 'rgba(28, 39, 35, 0.94)' : 'rgba(255,255,255,0.12)',
        color: isDarkTheme ? '#edf8f3' : '#edfdf4',
        border: isDarkTheme ? '1px solid rgba(157, 179, 170, 0.24)' : '1px solid rgba(255,255,255,0.12)',
        fontWeight: 700,
        boxShadow: isDarkTheme ? 'inset 0 0 0 1px rgba(255,255,255,0.02)' : 'none',
      },
      searchWrapper: {
        maxWidth: '620px',
        position: 'relative',
      },
      searchInput: {
        width: '100%',
        padding: '15px 20px 15px 47px',
        borderRadius: '12px',
        border: isDarkTheme ? '1px solid rgba(128, 176, 160, 0.2)' : 'none',
        background: isDarkTheme ? 'rgba(14, 25, 20, 0.9)' : '#fff',
        color: isDarkTheme ? '#edf9f1' : '#1f2937',
        fontSize: '14px',
        outline: 'none',
        boxShadow: isDarkTheme ? '0 12px 24px rgba(2, 6, 4, 0.24)' : '0 12px 24px rgba(11, 58, 42, 0.14)',
      },
      searchIcon: {
        position: 'absolute',
        left: '18px',
        top: '10px',
        color: isDarkTheme ? '#9fe7c0' : '#0d5c42',
        fontSize: '26px',
        lineHeight: 1,
        zIndex: 1,
      },
      catBar: {
        background: isDarkTheme ? '#101d18' : '#fff',
        borderBottom: isDarkTheme ? '1px solid rgba(123, 164, 146, 0.18)' : '1px solid #eef2f6',
        position: 'sticky',
        top: 0,
        zIndex: 100,
      },
      catContainer: {
        maxWidth: '1280px',
        margin: '0 auto',
        padding: '12px 24px',
        display: 'flex',
        gap: '8px',
        overflowX: 'auto',
        scrollbarWidth: 'thin',
      },
      catBtn: {
        padding: '8px 20px',
        borderRadius: '40px',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.2s',
        border: isDarkTheme ? '1px solid rgba(143, 170, 159, 0.18)' : '1px solid #e2e8f0',
        background: isDarkTheme ? '#14261d' : '#fff',
        color: isDarkTheme ? '#dfece5' : '#475569',
        whiteSpace: 'nowrap',
      },
      catBtnActive: {
        background: 'linear-gradient(135deg, #0e8f6a, #0a6b50)',
        borderColor: '#0d7c60',
        color: '#f0fff8',
        boxShadow: '0 10px 20px rgba(10,107,80,0.18)',
      },
      subcatBar: {
        background: isDarkTheme ? '#0f1b16' : '#f8fafc',
        borderBottom: isDarkTheme ? '1px solid rgba(123, 164, 146, 0.18)' : '1px solid #eef2f6',
      },
      subcatContainer: {
        maxWidth: '1280px',
        margin: '0 auto',
        padding: '8px 24px',
        display: 'flex',
        gap: '7px',
        overflowX: 'auto',
      },
      subcatBtn: {
        padding: '6px 13px',
        borderRadius: '8px',
        fontSize: '11px',
        fontWeight: '700',
        cursor: 'pointer',
        border: isDarkTheme ? '1px solid rgba(143, 170, 159, 0.18)' : '1px solid transparent',
        background: isDarkTheme ? '#14261d' : 'transparent',
        color: isDarkTheme ? '#cfe2d9' : '#64748b',
        whiteSpace: 'nowrap',
      },
      subcatBtnActive: {
        background: 'linear-gradient(135deg, #e7f7ef, #d9f1ea)',
        color: '#0b5d45',
        borderColor: '#a8dcc3',
        boxShadow: 'inset 0 0 0 1px rgba(45, 122, 99, 0.08)',
      },
      main: {
        maxWidth: '1280px',
        margin: '0 auto',
        padding: '32px 24px',
      },
      controls: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '0',
        flexWrap: 'wrap',
        gap: '16px',
      },
      stats: {
        fontSize: '14px',
        color: isDarkTheme ? '#bacac0' : '#64748b',
        fontWeight: '500',
      },
      sortSelect: {
        padding: '8px 16px',
        borderRadius: '8px',
        border: isDarkTheme ? '1px solid rgba(143, 170, 159, 0.18)' : '1px solid #e2e8f0',
        fontSize: '13px',
        background: isDarkTheme ? '#14261d' : '#fff',
        color: isDarkTheme ? '#edf9f1' : '#1f2937',
        cursor: 'pointer',
      },
      grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(230px, 1fr))',
        gap: '20px',
        marginBottom: '48px',
      },
      loadingGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(230px, 1fr))',
        gap: '20px',
      },
      skeletonCard: {
        height: '380px',
        background: isDarkTheme ? '#14261d' : '#fff',
        borderRadius: '12px',
        border: isDarkTheme ? '1px solid rgba(143, 170, 159, 0.18)' : '1px solid #eef2f6',
        animation: 'pulse 1.5s ease-in-out infinite',
      },
      emptyState: {
        textAlign: 'center',
        padding: '80px 24px',
        background: isDarkTheme ? '#132018' : '#fff',
        borderRadius: '16px',
        border: isDarkTheme ? '1px solid rgba(143, 170, 159, 0.18)' : '1px solid transparent',
      },
      emptyIcon: {
        fontSize: '64px',
        marginBottom: '16px',
      },
      emptyTitle: {
        fontSize: '20px',
        fontWeight: '600',
        color: isDarkTheme ? '#edf9f1' : '#1e293b',
        marginBottom: '8px',
      },
      emptyText: {
        fontSize: '14px',
        color: isDarkTheme ? '#bacac0' : '#64748b',
        marginBottom: '24px',
      },
      resetBtn: {
        padding: '10px 24px',
        background: '#059669',
        color: '#fff',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '600',
        cursor: 'pointer',
      },
      recentSection: {
        marginTop: '32px',
        paddingTop: '32px',
        borderTop: '1px solid #eef2f6',
      },
      recentTitle: {
        fontSize: '18px',
        fontWeight: '700',
        color: '#1e293b',
        marginBottom: '20px',
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
      },
      recentCount: {
        fontSize: '13px',
        fontWeight: '500',
        color: '#64748b',
        background: '#f1f5f9',
        padding: '2px 10px',
        borderRadius: '20px',
      },
      recentGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(230px, 1fr))',
        gap: '20px',
      },
    };
}
