export default {
  card: {
    background: 'linear-gradient(180deg, rgba(255,255,255,0.96) 0%, rgba(248,252,250,0.98) 100%)',
    borderRadius: '22px',
    overflow: 'hidden',
    border: '1px solid rgba(20,100,70,0.12)',
    transition: 'all 0.22s ease',
    cursor: 'pointer',
    minHeight: '366px',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    boxShadow: '0 16px 34px rgba(11, 58, 42, 0.08)',
    backdropFilter: 'blur(10px)',
  },
  imageWrapper: {
    position: 'relative',
    height: '220px',
    background: 'radial-gradient(ellipse at center, #ffffff 0%, #f3f8f3 56%, #e8f2eb 100%)',
    overflow: 'hidden',
    flexShrink: 0,
  },
  imageOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, rgba(16, 39, 28, 0.01) 0%, rgba(16, 39, 28, 0.05) 100%)',
    pointerEvents: 'none',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    objectPosition: 'center',
    boxSizing: 'border-box',
    padding: '10px',
    transition: 'transform 0.45s cubic-bezier(.2,.8,.2,1)',
    display: 'block',
  },
  placeholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #f0fdf4, #dcfce7)',
  },
  placeholderText: {
    fontSize: '48px',
    fontWeight: '700',
    color: '#86efac',
  },
  navBtn: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'rgba(0,0,0,0.6)',
    color: '#fff',
    border: 'none',
    borderRadius: '50%',
    width: '30px',
    height: '30px',
    fontSize: '20px',
    fontWeight: 'bold',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0,
    transition: 'opacity 0.2s',
    zIndex: 10,
  },
  counter: {
    position: 'absolute',
    bottom: '8px',
    right: '8px',
    background: 'rgba(0,0,0,0.7)',
    color: '#fff',
    fontSize: '10px',
    fontWeight: '600',
    padding: '2px 8px',
    borderRadius: '12px',
    zIndex: 10,
  },
  dots: {
    position: 'absolute',
    bottom: '8px',
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
    gap: '6px',
    zIndex: 10,
  },
  dotButton: {
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    border: 0,
    background: 'transparent',
    cursor: 'pointer',
  },
  dot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.5)',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    transition: 'all 0.2s',
  },
  dotActive: {
    width: '18px',
    borderRadius: '3px',
    background: '#fff',
  },
  badges: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    zIndex: 10,
  },
  categoryBadge: {
    position: 'absolute',
    top: '8px',
    left: '8px',
    maxWidth: '55%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    background: 'linear-gradient(135deg, rgba(255,255,255,0.96), rgba(231,255,242,0.92))',
    color: '#0d5c42',
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
    padding: '6px 10px',
    borderRadius: '20px',
    border: '1px solid rgba(15, 118, 110, 0.18)',
    boxShadow: '0 4px 12px rgba(15,23,42,0.14)',
    zIndex: 10,
  },
  badgeLocal: {
    background: '#047857',
    color: '#fff',
    fontSize: '10px',
    fontWeight: '600',
    padding: '3px 10px',
    borderRadius: '20px',
  },
  badgeDiscount: {
    background: 'linear-gradient(135deg,#b95f3b,#963f35)',
    color: '#fff',
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '.3px',
    padding: '4px 10px',
    borderRadius: '20px',
    boxShadow: '0 4px 12px rgba(111,46,31,.24)',
  },
  badgeDiscountUpcoming: {
    background: 'linear-gradient(135deg,#543d24,#795322)',
    border: '1px solid rgba(255,239,201,.45)',
    color: '#fff4d6',
    fontSize: '9px',
    fontWeight: '900',
    letterSpacing: '.25px',
    padding: '4px 8px',
    borderRadius: '20px',
    boxShadow: '0 4px 12px rgba(73,48,19,.24)',
    whiteSpace: 'nowrap',
  },
  badgeRestricted: {
    background: '#7c3aed',
    color: '#fff',
    fontSize: '10px',
    fontWeight: '600',
    padding: '3px 10px',
    borderRadius: '20px',
  },
  badgeLowStock: {
    background: '#f97316',
    color: '#fff',
    fontSize: '10px',
    fontWeight: '600',
    padding: '3px 10px',
    borderRadius: '20px',
  },
  badgeSoldOut: {
    background: '#dc2626',
    color: '#fff',
    fontSize: '10px',
    fontWeight: '600',
    padding: '3px 10px',
    borderRadius: '20px',
  },
  content: {
    padding: '16px 17px 17px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    flex: 1,
  },
  name: {
    margin: '0 0 6px',
    fontSize: '18px',
    fontWeight: '800',
    color: '#1c1a1a',
    lineHeight: '1.28',
    letterSpacing: '-0.04em',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  nameLink: {
    color: 'inherit',
    textDecoration: 'none',
  },
  description: {
    margin: '0 0 10px',
    fontSize: '13px',
    color: '#52606d',
    lineHeight: '1.5',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  productMeta: {
    margin: '-2px 0 8px',
    fontSize: '11px',
    color: '#566d77',
    fontWeight: '700',
    letterSpacing: '0.08em',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  priceRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    marginBottom: '12px',
  },
  price: {
    fontSize: '22px',
    fontWeight: '800',
    color: '#17141f',
    letterSpacing: '-0.05em',
  },
  priceAlt: {
    fontSize: '11px',
    color: '#7f8c98',
    fontWeight: '600',
    marginTop: '-8px',
    marginBottom: '10px',
  },
  originalPrice: {
    fontSize: '12px',
    color: '#829087',
    fontWeight: '600',
  },
  addButton: {
    background: 'linear-gradient(135deg,#1d7d5f,#104f3e)',
    color: '#fff',
    border: 'none',
    borderRadius: '12px',
    padding: '10px 12px',
    fontSize: '12px',
    fontWeight: '800',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 14px 24px rgba(13,92,66,0.18)',
    marginTop: 'auto',
    letterSpacing: '0.06em',
  },
  addButtonDisabled: {
    background: '#e2e8f0',
    color: '#94a3b8',
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
};
